import { useParams, useNavigate } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import { useAuth } from "../hooks/useAuth";
import { Printer, ArrowLeft } from "lucide-react";

/**
 * Show the PDF generated by backend for an order
 * Backend endpoint pattern: /api/ordenes/{id}/pdf
 */
export default function DetalleOrdenPDF() {
  const { id } = useParams();
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const backendUrl = import.meta.env.VITE_API_URL || "http://localhost:8000";
  const pdfUrl = `${backendUrl}/api/ordenes/${id}/pdf`;

  const handlePrint = () => {
    const printWindow = window.open(pdfUrl, "_blank");
    if (printWindow) {
      // optional: attempt to trigger print after load
      printWindow.addEventListener("load", () => {
        printWindow.focus();
        printWindow.print();
      });
    }
  };

  return (
    <div className="flex h-screen bg-gray-100">
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Header user={user} logout={logout} />

        <div className="p-6 flex flex-col items-center">
          <h1 className="text-3xl font-bold mb-6 text-center">Detalle de Orden #{id}</h1>

          <iframe
            src={pdfUrl}
            className="w-full max-w-4xl h-[700px] border rounded"
            title={`Orden ${id} PDF`}
          />

          <div className="mt-4 flex gap-4">
            <button
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700"
            >
              <ArrowLeft size={18} /> Volver
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-2 bg-green-700 text-white px-4 py-2 rounded hover:bg-green-800"
            >
              <Printer size={18} /> Imprimir PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}